// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package queries

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const countUpcomingConfirmedBookings = `-- name: CountUpcomingConfirmedBookings :one
SELECT count(*) FROM bookings WHERE page_id = $1 AND status = 'confirmed' AND start_at >= $2
`

type CountUpcomingConfirmedBookingsParams struct {
	PageID  string
	StartAt time.Time
}

func (q *Queries) CountUpcomingConfirmedBookings(ctx context.Context, arg CountUpcomingConfirmedBookingsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUpcomingConfirmedBookings, arg.PageID, arg.StartAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBookingPage = `-- name: GetBookingPage :one
SELECT id, organization_id, created_by, member_user_id, slug, title, description, location, timezone, slot_duration_min, buffer_before_min, buffer_after_min, min_notice_min, max_days_ahead, availability, date_overrides, google_sync, reminders, status, created_at, updated_at, deleted_at FROM booking_pages WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBookingPage(ctx context.Context, id string) (BookingPage, error) {
	row := q.db.QueryRowContext(ctx, getBookingPage, id)
	var i BookingPage
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.MemberUserID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Timezone,
		&i.SlotDurationMin,
		&i.BufferBeforeMin,
		&i.BufferAfterMin,
		&i.MinNoticeMin,
		&i.MaxDaysAhead,
		&i.Availability,
		&i.DateOverrides,
		&i.GoogleSync,
		&i.Reminders,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBookingPageByOrgSlug = `-- name: GetBookingPageByOrgSlug :one
SELECT id, organization_id, created_by, member_user_id, slug, title, description, location, timezone, slot_duration_min, buffer_before_min, buffer_after_min, min_notice_min, max_days_ahead, availability, date_overrides, google_sync, reminders, status, created_at, updated_at, deleted_at FROM booking_pages WHERE organization_id = $1 AND slug = $2 AND deleted_at IS NULL
`

type GetBookingPageByOrgSlugParams struct {
	OrganizationID int64
	Slug           string
}

func (q *Queries) GetBookingPageByOrgSlug(ctx context.Context, arg GetBookingPageByOrgSlugParams) (BookingPage, error) {
	row := q.db.QueryRowContext(ctx, getBookingPageByOrgSlug, arg.OrganizationID, arg.Slug)
	var i BookingPage
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.MemberUserID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Timezone,
		&i.SlotDurationMin,
		&i.BufferBeforeMin,
		&i.BufferAfterMin,
		&i.MinNoticeMin,
		&i.MaxDaysAhead,
		&i.Availability,
		&i.DateOverrides,
		&i.GoogleSync,
		&i.Reminders,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, logo, metadata, created_at, updated_at FROM organizations WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Logo,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBookingPage = `-- name: InsertBookingPage :exec

INSERT INTO booking_pages (
  id, organization_id, created_by, member_user_id, slug, title, description, location,
  timezone, slot_duration_min, buffer_before_min, buffer_after_min, min_notice_min,
  max_days_ahead, availability, date_overrides, google_sync, reminders, status,
  created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21
)
`

type InsertBookingPageParams struct {
	ID              string
	OrganizationID  int64
	CreatedBy       sql.NullInt64
	MemberUserID    sql.NullInt64
	Slug            string
	Title           string
	Description     sql.NullString
	Location        sql.NullString
	Timezone        string
	SlotDurationMin int32
	BufferBeforeMin int32
	BufferAfterMin  int32
	MinNoticeMin    int32
	MaxDaysAhead    int32
	Availability    json.RawMessage
	DateOverrides   pqtype.NullRawMessage
	GoogleSync      bool
	Reminders       bool
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// Task 2 (booking pages service) queries below.
func (q *Queries) InsertBookingPage(ctx context.Context, arg InsertBookingPageParams) error {
	_, err := q.db.ExecContext(ctx, insertBookingPage,
		arg.ID,
		arg.OrganizationID,
		arg.CreatedBy,
		arg.MemberUserID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.Timezone,
		arg.SlotDurationMin,
		arg.BufferBeforeMin,
		arg.BufferAfterMin,
		arg.MinNoticeMin,
		arg.MaxDaysAhead,
		arg.Availability,
		arg.DateOverrides,
		arg.GoogleSync,
		arg.Reminders,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listBookingPagesByOrg = `-- name: ListBookingPagesByOrg :many
SELECT id, organization_id, created_by, member_user_id, slug, title, description, location, timezone, slot_duration_min, buffer_before_min, buffer_after_min, min_notice_min, max_days_ahead, availability, date_overrides, google_sync, reminders, status, created_at, updated_at, deleted_at FROM booking_pages WHERE organization_id = $1 AND deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListBookingPagesByOrg(ctx context.Context, organizationID int64) ([]BookingPage, error) {
	rows, err := q.db.QueryContext(ctx, listBookingPagesByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingPage
	for rows.Next() {
		var i BookingPage
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.MemberUserID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.Timezone,
			&i.SlotDurationMin,
			&i.BufferBeforeMin,
			&i.BufferAfterMin,
			&i.MinNoticeMin,
			&i.MaxDaysAhead,
			&i.Availability,
			&i.DateOverrides,
			&i.GoogleSync,
			&i.Reminders,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteBookingPage = `-- name: SoftDeleteBookingPage :exec
UPDATE booking_pages SET deleted_at = $2, updated_at = $2 WHERE id = $1
`

type SoftDeleteBookingPageParams struct {
	ID        string
	DeletedAt sql.NullTime
}

func (q *Queries) SoftDeleteBookingPage(ctx context.Context, arg SoftDeleteBookingPageParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteBookingPage, arg.ID, arg.DeletedAt)
	return err
}

const updateBookingPage = `-- name: UpdateBookingPage :exec
UPDATE booking_pages SET
  slug = $2,
  title = $3,
  description = $4,
  location = $5,
  timezone = $6,
  slot_duration_min = $7,
  buffer_before_min = $8,
  buffer_after_min = $9,
  min_notice_min = $10,
  max_days_ahead = $11,
  availability = $12,
  date_overrides = $13,
  google_sync = $14,
  reminders = $15,
  status = $16,
  updated_at = $17
WHERE id = $1
`

type UpdateBookingPageParams struct {
	ID              string
	Slug            string
	Title           string
	Description     sql.NullString
	Location        sql.NullString
	Timezone        string
	SlotDurationMin int32
	BufferBeforeMin int32
	BufferAfterMin  int32
	MinNoticeMin    int32
	MaxDaysAhead    int32
	Availability    json.RawMessage
	DateOverrides   pqtype.NullRawMessage
	GoogleSync      bool
	Reminders       bool
	Status          string
	UpdatedAt       time.Time
}

func (q *Queries) UpdateBookingPage(ctx context.Context, arg UpdateBookingPageParams) error {
	_, err := q.db.ExecContext(ctx, updateBookingPage,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.Timezone,
		arg.SlotDurationMin,
		arg.BufferBeforeMin,
		arg.BufferAfterMin,
		arg.MinNoticeMin,
		arg.MaxDaysAhead,
		arg.Availability,
		arg.DateOverrides,
		arg.GoogleSync,
		arg.Reminders,
		arg.Status,
		arg.UpdatedAt,
	)
	return err
}

const updateOrganizationSlug = `-- name: UpdateOrganizationSlug :exec
UPDATE organizations SET slug = $2, updated_at = now() WHERE id = $1
`

type UpdateOrganizationSlugParams struct {
	ID   int64
	Slug string
}

func (q *Queries) UpdateOrganizationSlug(ctx context.Context, arg UpdateOrganizationSlugParams) error {
	_, err := q.db.ExecContext(ctx, updateOrganizationSlug, arg.ID, arg.Slug)
	return err
}
