// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package queries

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const countUpcomingConfirmedBookings = `-- name: CountUpcomingConfirmedBookings :one
SELECT count(*) FROM bookings WHERE page_id = $1 AND status = 'confirmed' AND start_at >= $2
`

type CountUpcomingConfirmedBookingsParams struct {
	PageID  string
	StartAt time.Time
}

func (q *Queries) CountUpcomingConfirmedBookings(ctx context.Context, arg CountUpcomingConfirmedBookingsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUpcomingConfirmedBookings, arg.PageID, arg.StartAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const disableGoogleSyncForMember = `-- name: DisableGoogleSyncForMember :exec
UPDATE booking_pages SET google_sync = false, updated_at = $2 WHERE member_user_id = $1
`

type DisableGoogleSyncForMemberParams struct {
	MemberUserID sql.NullInt64
	UpdatedAt    time.Time
}

// Ports disconnectGoogleSync (pages.ts): turns googleSync off on every booking page whose
// member_user_id is userId — the account row itself (accounts, Limen's) is left untouched; only
// this user's own pages stop trying to sync against it.
func (q *Queries) DisableGoogleSyncForMember(ctx context.Context, arg DisableGoogleSyncForMemberParams) error {
	_, err := q.db.ExecContext(ctx, disableGoogleSyncForMember, arg.MemberUserID, arg.UpdatedAt)
	return err
}

const getBooking = `-- name: GetBooking :one
SELECT id, page_id, start_at, end_at, visitor_name, visitor_email, visitor_note, visitor_locale, visitor_timezone, status, cancelled_by, manage_token_hash, google_event_id, created_at, updated_at FROM bookings WHERE id = $1
`

func (q *Queries) GetBooking(ctx context.Context, id string) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.StartAt,
		&i.EndAt,
		&i.VisitorName,
		&i.VisitorEmail,
		&i.VisitorNote,
		&i.VisitorLocale,
		&i.VisitorTimezone,
		&i.Status,
		&i.CancelledBy,
		&i.ManageTokenHash,
		&i.GoogleEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingPage = `-- name: GetBookingPage :one
SELECT id, organization_id, created_by, member_user_id, slug, title, description, location, timezone, slot_duration_min, buffer_before_min, buffer_after_min, min_notice_min, max_days_ahead, availability, date_overrides, google_sync, reminders, status, created_at, updated_at, deleted_at FROM booking_pages WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBookingPage(ctx context.Context, id string) (BookingPage, error) {
	row := q.db.QueryRowContext(ctx, getBookingPage, id)
	var i BookingPage
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.MemberUserID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Timezone,
		&i.SlotDurationMin,
		&i.BufferBeforeMin,
		&i.BufferAfterMin,
		&i.MinNoticeMin,
		&i.MaxDaysAhead,
		&i.Availability,
		&i.DateOverrides,
		&i.GoogleSync,
		&i.Reminders,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBookingPageByOrgSlug = `-- name: GetBookingPageByOrgSlug :one
SELECT id, organization_id, created_by, member_user_id, slug, title, description, location, timezone, slot_duration_min, buffer_before_min, buffer_after_min, min_notice_min, max_days_ahead, availability, date_overrides, google_sync, reminders, status, created_at, updated_at, deleted_at FROM booking_pages WHERE organization_id = $1 AND slug = $2 AND deleted_at IS NULL
`

type GetBookingPageByOrgSlugParams struct {
	OrganizationID int64
	Slug           string
}

func (q *Queries) GetBookingPageByOrgSlug(ctx context.Context, arg GetBookingPageByOrgSlugParams) (BookingPage, error) {
	row := q.db.QueryRowContext(ctx, getBookingPageByOrgSlug, arg.OrganizationID, arg.Slug)
	var i BookingPage
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.MemberUserID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Timezone,
		&i.SlotDurationMin,
		&i.BufferBeforeMin,
		&i.BufferAfterMin,
		&i.MinNoticeMin,
		&i.MaxDaysAhead,
		&i.Availability,
		&i.DateOverrides,
		&i.GoogleSync,
		&i.Reminders,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBookingPageByOrgSlugForUpdate = `-- name: GetBookingPageByOrgSlugForUpdate :one

SELECT id, organization_id, created_by, member_user_id, slug, title, description, location, timezone, slot_duration_min, buffer_before_min, buffer_after_min, min_notice_min, max_days_ahead, availability, date_overrides, google_sync, reminders, status, created_at, updated_at, deleted_at FROM booking_pages WHERE organization_id = $1 AND slug = $2 AND deleted_at IS NULL FOR UPDATE
`

type GetBookingPageByOrgSlugForUpdateParams struct {
	OrganizationID int64
	Slug           string
}

// Task 3 (booking creation/manage service) queries below.
// Locks the page row for the duration of the enclosing transaction — Book/Reschedule's own
// invariant lock (see bookings.go's package doc comment): serializes every concurrent
// book/reschedule attempt against THIS page, so the "recompute busy intervals, then insert"
// sequence below can never interleave across transactions.
func (q *Queries) GetBookingPageByOrgSlugForUpdate(ctx context.Context, arg GetBookingPageByOrgSlugForUpdateParams) (BookingPage, error) {
	row := q.db.QueryRowContext(ctx, getBookingPageByOrgSlugForUpdate, arg.OrganizationID, arg.Slug)
	var i BookingPage
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.MemberUserID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Timezone,
		&i.SlotDurationMin,
		&i.BufferBeforeMin,
		&i.BufferAfterMin,
		&i.MinNoticeMin,
		&i.MaxDaysAhead,
		&i.Availability,
		&i.DateOverrides,
		&i.GoogleSync,
		&i.Reminders,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBookingPageForUpdate = `-- name: GetBookingPageForUpdate :one
SELECT id, organization_id, created_by, member_user_id, slug, title, description, location, timezone, slot_duration_min, buffer_before_min, buffer_after_min, min_notice_min, max_days_ahead, availability, date_overrides, google_sync, reminders, status, created_at, updated_at, deleted_at FROM booking_pages WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

// Same lock as GetBookingPageByOrgSlugForUpdate, keyed by id instead of (org, slug) — used by
// Reschedule, which already has the booking's page_id in hand.
func (q *Queries) GetBookingPageForUpdate(ctx context.Context, id string) (BookingPage, error) {
	row := q.db.QueryRowContext(ctx, getBookingPageForUpdate, id)
	var i BookingPage
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.MemberUserID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Timezone,
		&i.SlotDurationMin,
		&i.BufferBeforeMin,
		&i.BufferAfterMin,
		&i.MinNoticeMin,
		&i.MaxDaysAhead,
		&i.Availability,
		&i.DateOverrides,
		&i.GoogleSync,
		&i.Reminders,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGoogleAccount = `-- name: GetGoogleAccount :one
SELECT id, access_token, refresh_token, access_token_expires_at
FROM accounts
WHERE user_id = $1 AND provider = 'google'
ORDER BY id
LIMIT 1
`

type GetGoogleAccountRow struct {
	ID                   int64
	AccessToken          string
	RefreshToken         sql.NullString
	AccessTokenExpiresAt sql.NullTime
}

// The linked Google account row backing a page's member — google.go's own token store. Limen owns
// this table (migrations/00002_auth.sql); this package only ever reads/refreshes the one row a
// Google Calendar sync needs, never any other provider's row.
func (q *Queries) GetGoogleAccount(ctx context.Context, userID int64) (GetGoogleAccountRow, error) {
	row := q.db.QueryRowContext(ctx, getGoogleAccount, userID)
	var i GetGoogleAccountRow
	err := row.Scan(
		&i.ID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, slug, logo, metadata, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id int64) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Logo,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, logo, metadata, created_at, updated_at FROM organizations WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Logo,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one

SELECT id, email, password, email_verified_at, first_name, last_name, created_at, updated_at, two_factor_enabled FROM users WHERE id = $1
`

// Task 4 (booking mail set and reminders) queries below.
// The page's memberUserId owner — who receives the organiser half of a lifecycle mail (emails.go).
func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.EmailVerifiedAt,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TwoFactorEnabled,
	)
	return i, err
}

const insertBooking = `-- name: InsertBooking :exec
INSERT INTO bookings (
  id, page_id, start_at, end_at, visitor_name, visitor_email, visitor_note, visitor_locale,
  visitor_timezone, status, cancelled_by, manage_token_hash, google_event_id, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type InsertBookingParams struct {
	ID              string
	PageID          string
	StartAt         time.Time
	EndAt           time.Time
	VisitorName     string
	VisitorEmail    string
	VisitorNote     sql.NullString
	VisitorLocale   sql.NullString
	VisitorTimezone string
	Status          string
	CancelledBy     sql.NullString
	ManageTokenHash string
	GoogleEventID   sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) InsertBooking(ctx context.Context, arg InsertBookingParams) error {
	_, err := q.db.ExecContext(ctx, insertBooking,
		arg.ID,
		arg.PageID,
		arg.StartAt,
		arg.EndAt,
		arg.VisitorName,
		arg.VisitorEmail,
		arg.VisitorNote,
		arg.VisitorLocale,
		arg.VisitorTimezone,
		arg.Status,
		arg.CancelledBy,
		arg.ManageTokenHash,
		arg.GoogleEventID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertBookingPage = `-- name: InsertBookingPage :exec

INSERT INTO booking_pages (
  id, organization_id, created_by, member_user_id, slug, title, description, location,
  timezone, slot_duration_min, buffer_before_min, buffer_after_min, min_notice_min,
  max_days_ahead, availability, date_overrides, google_sync, reminders, status,
  created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21
)
`

type InsertBookingPageParams struct {
	ID              string
	OrganizationID  int64
	CreatedBy       sql.NullInt64
	MemberUserID    sql.NullInt64
	Slug            string
	Title           string
	Description     sql.NullString
	Location        sql.NullString
	Timezone        string
	SlotDurationMin int32
	BufferBeforeMin int32
	BufferAfterMin  int32
	MinNoticeMin    int32
	MaxDaysAhead    int32
	Availability    json.RawMessage
	DateOverrides   pqtype.NullRawMessage
	GoogleSync      bool
	Reminders       bool
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// Task 2 (booking pages service) queries below.
func (q *Queries) InsertBookingPage(ctx context.Context, arg InsertBookingPageParams) error {
	_, err := q.db.ExecContext(ctx, insertBookingPage,
		arg.ID,
		arg.OrganizationID,
		arg.CreatedBy,
		arg.MemberUserID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.Timezone,
		arg.SlotDurationMin,
		arg.BufferBeforeMin,
		arg.BufferAfterMin,
		arg.MinNoticeMin,
		arg.MaxDaysAhead,
		arg.Availability,
		arg.DateOverrides,
		arg.GoogleSync,
		arg.Reminders,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const isOrgMember = `-- name: IsOrgMember :one

SELECT EXISTS (
  SELECT 1 FROM organization_members WHERE organization_id = $1 AND user_id = $2
) AS is_member
`

type IsOrgMemberParams struct {
	OrganizationID int64
	UserID         int64
}

// Task 6 (HTTP surface — accumulated requirement (a), the canManageContent-shaped authz gate)
// queries below.
// Ports the membership-is-the-authority rule (canManageContent's own membership precondition —
// see internal/polls/queries's identical query for the sibling rationale): does userId belong to
// organizationId at all, regardless of role?
func (q *Queries) IsOrgMember(ctx context.Context, arg IsOrgMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isOrgMember, arg.OrganizationID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listBookingPagesByOrg = `-- name: ListBookingPagesByOrg :many
SELECT id, organization_id, created_by, member_user_id, slug, title, description, location, timezone, slot_duration_min, buffer_before_min, buffer_after_min, min_notice_min, max_days_ahead, availability, date_overrides, google_sync, reminders, status, created_at, updated_at, deleted_at FROM booking_pages WHERE organization_id = $1 AND deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListBookingPagesByOrg(ctx context.Context, organizationID int64) ([]BookingPage, error) {
	rows, err := q.db.QueryContext(ctx, listBookingPagesByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingPage
	for rows.Next() {
		var i BookingPage
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.MemberUserID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.Timezone,
			&i.SlotDurationMin,
			&i.BufferBeforeMin,
			&i.BufferAfterMin,
			&i.MinNoticeMin,
			&i.MaxDaysAhead,
			&i.Availability,
			&i.DateOverrides,
			&i.GoogleSync,
			&i.Reminders,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsInRange = `-- name: ListBookingsInRange :many
SELECT id, page_id, start_at, end_at, visitor_name, visitor_email, visitor_note, visitor_locale, visitor_timezone, status, cancelled_by, manage_token_hash, google_event_id, created_at, updated_at FROM bookings
WHERE page_id = $1
  AND start_at < $2
  AND end_at > $3
ORDER BY start_at
`

type ListBookingsInRangeParams struct {
	PageID    string
	RangeTo   time.Time
	RangeFrom time.Time
}

// Every booking (any status) on a page overlapping [range_from, range_to) — ListPageBookings'
// own query, unfiltered by status (matching listBookings, bookings.ts).
func (q *Queries) ListBookingsInRange(ctx context.Context, arg ListBookingsInRangeParams) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsInRange, arg.PageID, arg.RangeTo, arg.RangeFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.StartAt,
			&i.EndAt,
			&i.VisitorName,
			&i.VisitorEmail,
			&i.VisitorNote,
			&i.VisitorLocale,
			&i.VisitorTimezone,
			&i.Status,
			&i.CancelledBy,
			&i.ManageTokenHash,
			&i.GoogleEventID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfirmedBookingsInRange = `-- name: ListConfirmedBookingsInRange :many
SELECT id, page_id, start_at, end_at, visitor_name, visitor_email, visitor_note, visitor_locale, visitor_timezone, status, cancelled_by, manage_token_hash, google_event_id, created_at, updated_at FROM bookings
WHERE page_id = $1
  AND status = 'confirmed'
  AND start_at < $2
  AND end_at > $3
ORDER BY start_at
`

type ListConfirmedBookingsInRangeParams struct {
	PageID    string
	RangeTo   time.Time
	RangeFrom time.Time
}

// Confirmed bookings on a page overlapping [range_from, range_to) as their raw stored interval —
// see bookedIntervalsForPage's (bookings.go) doc comment on why no buffer is applied here.
func (q *Queries) ListConfirmedBookingsInRange(ctx context.Context, arg ListConfirmedBookingsInRangeParams) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listConfirmedBookingsInRange, arg.PageID, arg.RangeTo, arg.RangeFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.StartAt,
			&i.EndAt,
			&i.VisitorName,
			&i.VisitorEmail,
			&i.VisitorNote,
			&i.VisitorLocale,
			&i.VisitorTimezone,
			&i.Status,
			&i.CancelledBy,
			&i.ManageTokenHash,
			&i.GoogleEventID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memberHasManagingRole = `-- name: MemberHasManagingRole :one
SELECT EXISTS (
  SELECT 1 FROM organization_members om
  JOIN organization_member_roles omr ON omr.member_id = om.id
  WHERE om.organization_id = $1 AND om.user_id = $2 AND omr.role IN ('owner', 'admin')
) AS has_role
`

type MemberHasManagingRoleParams struct {
	OrganizationID int64
	UserID         int64
}

// Ports canManageContent's role half (org-roles.ts): does userId hold an 'owner' or 'admin' role
// in organizationId? (The creator-manages-their-own-content half is checked separately by the
// caller against the resource's own createdBy — this query only ever answers the role question.)
func (q *Queries) MemberHasManagingRole(ctx context.Context, arg MemberHasManagingRoleParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, memberHasManagingRole, arg.OrganizationID, arg.UserID)
	var has_role bool
	err := row.Scan(&has_role)
	return has_role, err
}

const memberHasOwnerRole = `-- name: MemberHasOwnerRole :one
SELECT EXISTS (
  SELECT 1 FROM organization_members om
  JOIN organization_member_roles omr ON omr.member_id = om.id
  WHERE om.organization_id = $1 AND om.user_id = $2 AND omr.role = 'owner'
) AS has_role
`

type MemberHasOwnerRoleParams struct {
	OrganizationID int64
	UserID         int64
}

// Ports requireOwnerRole's own predicate (org-roles.ts): does userId hold the 'owner' role
// specifically (not admin) in organizationId? Used only by SetOrgSlug/org-handle's own
// RequireOwnerRole (authz.go) — every other owner-facing route accepts admin too
// (MemberHasManagingRole above).
func (q *Queries) MemberHasOwnerRole(ctx context.Context, arg MemberHasOwnerRoleParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, memberHasOwnerRole, arg.OrganizationID, arg.UserID)
	var has_role bool
	err := row.Scan(&has_role)
	return has_role, err
}

const softDeleteBookingPage = `-- name: SoftDeleteBookingPage :exec
UPDATE booking_pages SET deleted_at = $2, updated_at = $2 WHERE id = $1
`

type SoftDeleteBookingPageParams struct {
	ID        string
	DeletedAt sql.NullTime
}

func (q *Queries) SoftDeleteBookingPage(ctx context.Context, arg SoftDeleteBookingPageParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteBookingPage, arg.ID, arg.DeletedAt)
	return err
}

const updateBookingGoogleEventID = `-- name: UpdateBookingGoogleEventID :exec

UPDATE bookings SET google_event_id = $2, updated_at = $3 WHERE id = $1
`

type UpdateBookingGoogleEventIDParams struct {
	ID            string
	GoogleEventID sql.NullString
	UpdatedAt     time.Time
}

// Task 5 (Google Calendar sync) queries below.
// Persists (or clears, when null) the booking's known Google Calendar event id. See
// Service.SetGoogleEventID (google.go).
func (q *Queries) UpdateBookingGoogleEventID(ctx context.Context, arg UpdateBookingGoogleEventIDParams) error {
	_, err := q.db.ExecContext(ctx, updateBookingGoogleEventID, arg.ID, arg.GoogleEventID, arg.UpdatedAt)
	return err
}

const updateBookingPage = `-- name: UpdateBookingPage :exec
UPDATE booking_pages SET
  slug = $2,
  title = $3,
  description = $4,
  location = $5,
  timezone = $6,
  slot_duration_min = $7,
  buffer_before_min = $8,
  buffer_after_min = $9,
  min_notice_min = $10,
  max_days_ahead = $11,
  availability = $12,
  date_overrides = $13,
  google_sync = $14,
  reminders = $15,
  status = $16,
  updated_at = $17
WHERE id = $1
`

type UpdateBookingPageParams struct {
	ID              string
	Slug            string
	Title           string
	Description     sql.NullString
	Location        sql.NullString
	Timezone        string
	SlotDurationMin int32
	BufferBeforeMin int32
	BufferAfterMin  int32
	MinNoticeMin    int32
	MaxDaysAhead    int32
	Availability    json.RawMessage
	DateOverrides   pqtype.NullRawMessage
	GoogleSync      bool
	Reminders       bool
	Status          string
	UpdatedAt       time.Time
}

func (q *Queries) UpdateBookingPage(ctx context.Context, arg UpdateBookingPageParams) error {
	_, err := q.db.ExecContext(ctx, updateBookingPage,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.Timezone,
		arg.SlotDurationMin,
		arg.BufferBeforeMin,
		arg.BufferAfterMin,
		arg.MinNoticeMin,
		arg.MaxDaysAhead,
		arg.Availability,
		arg.DateOverrides,
		arg.GoogleSync,
		arg.Reminders,
		arg.Status,
		arg.UpdatedAt,
	)
	return err
}

const updateBookingSchedule = `-- name: UpdateBookingSchedule :exec
UPDATE bookings SET start_at = $2, end_at = $3, updated_at = $4 WHERE id = $1
`

type UpdateBookingScheduleParams struct {
	ID        string
	StartAt   time.Time
	EndAt     time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpdateBookingSchedule(ctx context.Context, arg UpdateBookingScheduleParams) error {
	_, err := q.db.ExecContext(ctx, updateBookingSchedule,
		arg.ID,
		arg.StartAt,
		arg.EndAt,
		arg.UpdatedAt,
	)
	return err
}

const updateBookingStatus = `-- name: UpdateBookingStatus :exec
UPDATE bookings SET status = $2, cancelled_by = $3, updated_at = $4 WHERE id = $1
`

type UpdateBookingStatusParams struct {
	ID          string
	Status      string
	CancelledBy sql.NullString
	UpdatedAt   time.Time
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateBookingStatus,
		arg.ID,
		arg.Status,
		arg.CancelledBy,
		arg.UpdatedAt,
	)
	return err
}

const updateGoogleAccountToken = `-- name: UpdateGoogleAccountToken :exec
UPDATE accounts
SET access_token = $2, refresh_token = $3, access_token_expires_at = $4, updated_at = $5
WHERE id = $1
`

type UpdateGoogleAccountTokenParams struct {
	ID                   int64
	AccessToken          string
	RefreshToken         sql.NullString
	AccessTokenExpiresAt sql.NullTime
	UpdatedAt            time.Time
}

// Persists a refreshed access (and, when Google issued a new one, refresh) token back onto the
// account row google.go just refreshed it from.
func (q *Queries) UpdateGoogleAccountToken(ctx context.Context, arg UpdateGoogleAccountTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateGoogleAccountToken,
		arg.ID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.AccessTokenExpiresAt,
		arg.UpdatedAt,
	)
	return err
}

const updateOrganizationSlug = `-- name: UpdateOrganizationSlug :exec
UPDATE organizations SET slug = $2, updated_at = now() WHERE id = $1
`

type UpdateOrganizationSlugParams struct {
	ID   int64
	Slug string
}

func (q *Queries) UpdateOrganizationSlug(ctx context.Context, arg UpdateOrganizationSlugParams) error {
	_, err := q.db.ExecContext(ctx, updateOrganizationSlug, arg.ID, arg.Slug)
	return err
}
