// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Account struct {
	ID                   int64
	UserID               int64
	Provider             string
	ProviderAccountID    sql.NullString
	AccessToken          string
	RefreshToken         sql.NullString
	AccessTokenExpiresAt sql.NullTime
	Scope                string
	IDToken              sql.NullString
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Booking struct {
	ID              string
	PageID          string
	StartAt         time.Time
	EndAt           time.Time
	VisitorName     string
	VisitorEmail    string
	VisitorNote     sql.NullString
	VisitorLocale   sql.NullString
	VisitorTimezone string
	Status          string
	CancelledBy     sql.NullString
	ManageTokenHash string
	GoogleEventID   sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type BookingPage struct {
	ID              string
	OrganizationID  int64
	CreatedBy       sql.NullInt64
	MemberUserID    sql.NullInt64
	Slug            string
	Title           string
	Description     sql.NullString
	Location        sql.NullString
	Timezone        string
	SlotDurationMin int32
	BufferBeforeMin int32
	BufferAfterMin  int32
	MinNoticeMin    int32
	MaxDaysAhead    int32
	Availability    json.RawMessage
	DateOverrides   pqtype.NullRawMessage
	GoogleSync      bool
	Reminders       bool
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
}

type Comment struct {
	ID            string
	PollID        string
	AuthorName    string
	ParticipantID sql.NullString
	UserID        sql.NullInt64
	Body          string
	CreatedAt     time.Time
	DeletedAt     sql.NullTime
}

type LimenRateLimit struct {
	ID            int64
	Key           string
	Count         int32
	LastRequestAt int64
}

type NotificationPref struct {
	UserID    int64
	Channels  pqtype.NullRawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type NotificationSubscription struct {
	ScopeType string
	ScopeID   string
	UserID    int64
	Source    string
	Channels  pqtype.NullRawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Organization struct {
	ID        int64
	Name      string
	Slug      string
	Logo      sql.NullString
	Metadata  pqtype.NullRawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OrganizationInvitation struct {
	ID             int64
	OrganizationID int64
	InviterID      sql.NullInt64
	Email          string
	Roles          sql.NullString
	Status         string
	Token          string
	ExpiresAt      sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type OrganizationMember struct {
	ID             int64
	OrganizationID int64
	UserID         int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type OrganizationMemberRole struct {
	ID             int64
	MemberID       int64
	OrganizationID int64
	Role           sql.NullString
	CreatedAt      time.Time
}

type Participant struct {
	ID            string
	PollID        string
	Name          string
	Email         sql.NullString
	UserID        sql.NullInt64
	EditTokenHash sql.NullString
	Locale        sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Poll struct {
	ID                      string
	OrganizationID          int64
	CreatedBy               sql.NullInt64
	Type                    string
	Title                   string
	Description             sql.NullString
	Location                sql.NullString
	Timezone                string
	Status                  string
	DeadlineAt              sql.NullTime
	FinalizedOptionID       sql.NullString
	RequireParticipantEmail bool
	AllowComments           bool
	AllowIfNeedBe           bool
	SignupMaxClaims         int32
	CreatedAt               time.Time
	UpdatedAt               time.Time
	DeletedAt               sql.NullTime
}

type PollOption struct {
	ID       string
	PollID   string
	Position int32
	Kind     string
	StartAt  sql.NullTime
	EndAt    sql.NullTime
	Label    sql.NullString
	Capacity sql.NullInt32
}

type RateLimit struct {
	Key     string
	Count   int32
	ResetAt time.Time
}

type RoomEvent struct {
	ID        int64
	RoomKey   string
	Event     json.RawMessage
	CreatedAt time.Time
}

type RoomState struct {
	RoomKey   string
	Data      json.RawMessage
	UpdatedAt time.Time
}

type ScheduledJob struct {
	ID          string
	Kind        string
	RoomKey     sql.NullString
	RunAt       time.Time
	Payload     pqtype.NullRawMessage
	Attempts    int32
	MaxAttempts int32
	LockedBy    sql.NullString
	LockedAt    sql.NullTime
	LastError   sql.NullString
	CreatedAt   time.Time
}

type Session struct {
	ID                   int64
	Token                string
	UserID               int64
	CreatedAt            time.Time
	ExpiresAt            time.Time
	LastAccess           time.Time
	Metadata             pqtype.NullRawMessage
	ActiveOrganizationID sql.NullInt64
}

type StaffUser struct {
	UserID    int64
	CreatedAt time.Time
}

type TwoFactor struct {
	ID          int64
	UserID      int64
	Secret      sql.NullString
	BackupCodes sql.NullString
}

type User struct {
	ID               int64
	Email            string
	Password         sql.NullString
	EmailVerifiedAt  sql.NullTime
	FirstName        sql.NullString
	LastName         sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
	TwoFactorEnabled bool
}

type Verification struct {
	ID        int64
	Subject   string
	Value     string
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Vote struct {
	ParticipantID string
	OptionID      string
	Answer        string
}

type WsPresence struct {
	RoomKey     string
	ReplicaID   string
	Count       int32
	HeartbeatAt time.Time
}
