// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"
)

type Querier interface {
	// Ports disconnectGoogleSync (pages.ts): turns googleSync off on every booking page whose
	// member_user_id is userId — the account row itself (accounts, Limen's) is left untouched; only
	// this user's own pages stop trying to sync against it.
	DisableGoogleSyncForMember(ctx context.Context, arg DisableGoogleSyncForMemberParams) error
	GetBooking(ctx context.Context, id string) (Booking, error)
	// M2/M7 (bookings.go): locks the booking row for the duration of the enclosing transaction.
	// Cancel takes this alone (it never touches the page row — there's no availability invariant to
	// protect on a cancel); Reschedule takes it too, AFTER GetBookingPageForUpdate (lock order is
	// always page then booking — see Reschedule's own doc comment for why that order, and why it
	// never deadlocks against Cancel, which only ever takes this one lock).
	GetBookingForUpdate(ctx context.Context, id string) (Booking, error)
	GetBookingPage(ctx context.Context, id string) (BookingPage, error)
	GetBookingPageByOrgSlug(ctx context.Context, arg GetBookingPageByOrgSlugParams) (BookingPage, error)
	// Task 3 (booking creation/manage service) queries below.
	// Locks the page row for the duration of the enclosing transaction — Book/Reschedule's own
	// invariant lock (see bookings.go's package doc comment): serializes every concurrent
	// book/reschedule attempt against THIS page, so the "recompute busy intervals, then insert"
	// sequence below can never interleave across transactions.
	GetBookingPageByOrgSlugForUpdate(ctx context.Context, arg GetBookingPageByOrgSlugForUpdateParams) (BookingPage, error)
	// Same lock as GetBookingPageByOrgSlugForUpdate, keyed by id instead of (org, slug) — used by
	// Reschedule, which already has the booking's page_id in hand.
	GetBookingPageForUpdate(ctx context.Context, id string) (BookingPage, error)
	// The linked Google account row backing a page's member — google.go's own token store. Limen owns
	// this table (migrations/00002_auth.sql); this package only ever reads/refreshes the one row a
	// Google Calendar sync needs, never any other provider's row.
	GetGoogleAccount(ctx context.Context, userID int64) (GetGoogleAccountRow, error)
	GetOrganization(ctx context.Context, id int64) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	// Task 4 (booking mail set and reminders) queries below.
	// The page's memberUserId owner — who receives the organiser half of a lifecycle mail (emails.go).
	GetUser(ctx context.Context, id int64) (User, error)
	InsertBooking(ctx context.Context, arg InsertBookingParams) error
	// Task 2 (booking pages service) queries below.
	InsertBookingPage(ctx context.Context, arg InsertBookingPageParams) error
	// Task 6 (HTTP surface — accumulated requirement (a), the canManageContent-shaped authz gate)
	// queries below.
	// Ports the membership-is-the-authority rule (canManageContent's own membership precondition —
	// see internal/polls/queries's identical query for the sibling rationale): does userId belong to
	// organizationId at all, regardless of role?
	IsOrgMember(ctx context.Context, arg IsOrgMemberParams) (bool, error)
	// ListMyPages' one-query list (pages.go): each live page with its count of confirmed bookings
	// starting at/after start_at, via a LATERAL aggregate — count(*) always yields exactly one row,
	// so a plain (CROSS) JOIN LATERAL is equivalent to the LEFT JOIN LATERAL + COALESCE form and
	// keeps the generated column a non-null bigint. Replaces the former per-page
	// CountUpcomingConfirmedBookings round trip (N+1).
	ListBookingPageSummariesByOrg(ctx context.Context, arg ListBookingPageSummariesByOrgParams) ([]ListBookingPageSummariesByOrgRow, error)
	// Every booking (any status) on a page overlapping [range_from, range_to) — ListPageBookings'
	// own query, unfiltered by status (matching listBookings, bookings.ts).
	ListBookingsInRange(ctx context.Context, arg ListBookingsInRangeParams) ([]Booking, error)
	// Confirmed bookings on a page overlapping [range_from, range_to) as their raw stored interval —
	// see bookedIntervalsForPage's (bookings.go) doc comment on why no buffer is applied here.
	ListConfirmedBookingsInRange(ctx context.Context, arg ListConfirmedBookingsInRangeParams) ([]Booking, error)
	// Ports canManageContent's role half (org-roles.ts): does userId hold an 'owner' or 'admin' role
	// in organizationId? (The creator-manages-their-own-content half is checked separately by the
	// caller against the resource's own createdBy — this query only ever answers the role question.)
	MemberHasManagingRole(ctx context.Context, arg MemberHasManagingRoleParams) (bool, error)
	// Ports requireOwnerRole's own predicate (org-roles.ts): does userId hold the 'owner' role
	// specifically (not admin) in organizationId? Used only by SetOrgSlug/org-handle's own
	// RequireOwnerRole (authz.go) — every other owner-facing route accepts admin too
	// (MemberHasManagingRole above).
	MemberHasOwnerRole(ctx context.Context, arg MemberHasOwnerRoleParams) (bool, error)
	SoftDeleteBookingPage(ctx context.Context, arg SoftDeleteBookingPageParams) error
	// Task 5 (Google Calendar sync) queries below.
	// Persists (or clears, when null) the booking's known Google Calendar event id. See
	// Service.SetGoogleEventID (google.go).
	UpdateBookingGoogleEventID(ctx context.Context, arg UpdateBookingGoogleEventIDParams) error
	UpdateBookingPage(ctx context.Context, arg UpdateBookingPageParams) error
	UpdateBookingSchedule(ctx context.Context, arg UpdateBookingScheduleParams) error
	UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) error
	// Persists a refreshed access (and, when Google issued a new one, refresh) token back onto the
	// account row google.go just refreshed it from.
	UpdateGoogleAccountToken(ctx context.Context, arg UpdateGoogleAccountTokenParams) error
	UpdateOrganizationSlug(ctx context.Context, arg UpdateOrganizationSlugParams) error
}

var _ Querier = (*Queries)(nil)
