// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"
)

type Querier interface {
	CountUpcomingConfirmedBookings(ctx context.Context, arg CountUpcomingConfirmedBookingsParams) (int64, error)
	GetBookingPage(ctx context.Context, id string) (BookingPage, error)
	GetBookingPageByOrgSlug(ctx context.Context, arg GetBookingPageByOrgSlugParams) (BookingPage, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	// Task 2 (booking pages service) queries below.
	InsertBookingPage(ctx context.Context, arg InsertBookingPageParams) error
	ListBookingPagesByOrg(ctx context.Context, organizationID int64) ([]BookingPage, error)
	SoftDeleteBookingPage(ctx context.Context, arg SoftDeleteBookingPageParams) error
	UpdateBookingPage(ctx context.Context, arg UpdateBookingPageParams) error
	UpdateOrganizationSlug(ctx context.Context, arg UpdateOrganizationSlugParams) error
}

var _ Querier = (*Queries)(nil)
