// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: polls.sql

package queries

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const countYesVotesForOption = `-- name: CountYesVotesForOption :one
SELECT count(*) FROM votes WHERE option_id = $1 AND answer = 'yes'
`

func (q *Queries) CountYesVotesForOption(ctx context.Context, optionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countYesVotesForOption, optionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteNotificationSubscription = `-- name: DeleteNotificationSubscription :exec
DELETE FROM notification_subscriptions WHERE scope_type = $1 AND scope_id = $2 AND user_id = $3
`

type DeleteNotificationSubscriptionParams struct {
	ScopeType string
	ScopeID   string
	UserID    int64
}

func (q *Queries) DeleteNotificationSubscription(ctx context.Context, arg DeleteNotificationSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationSubscription, arg.ScopeType, arg.ScopeID, arg.UserID)
	return err
}

const deleteParticipant = `-- name: DeleteParticipant :exec
DELETE FROM participants WHERE id = $1
`

func (q *Queries) DeleteParticipant(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteParticipant, id)
	return err
}

const deletePollOption = `-- name: DeletePollOption :exec
DELETE FROM poll_options WHERE id = $1
`

func (q *Queries) DeletePollOption(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePollOption, id)
	return err
}

const deleteVote = `-- name: DeleteVote :exec
DELETE FROM votes WHERE participant_id = $1 AND option_id = $2
`

type DeleteVoteParams struct {
	ParticipantID string
	OptionID      string
}

func (q *Queries) DeleteVote(ctx context.Context, arg DeleteVoteParams) error {
	_, err := q.db.ExecContext(ctx, deleteVote, arg.ParticipantID, arg.OptionID)
	return err
}

const deleteVotesByParticipant = `-- name: DeleteVotesByParticipant :exec
DELETE FROM votes WHERE participant_id = $1
`

func (q *Queries) DeleteVotesByParticipant(ctx context.Context, participantID string) error {
	_, err := q.db.ExecContext(ctx, deleteVotesByParticipant, participantID)
	return err
}

const finalizePoll = `-- name: FinalizePoll :exec
UPDATE polls SET finalized_option_id = $2, status = $3, updated_at = $4 WHERE id = $1
`

type FinalizePollParams struct {
	ID                string
	FinalizedOptionID sql.NullString
	Status            string
	UpdatedAt         time.Time
}

func (q *Queries) FinalizePoll(ctx context.Context, arg FinalizePollParams) error {
	_, err := q.db.ExecContext(ctx, finalizePoll,
		arg.ID,
		arg.FinalizedOptionID,
		arg.Status,
		arg.UpdatedAt,
	)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, poll_id, author_name, participant_id, user_id, body, created_at, deleted_at FROM comments WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetComment(ctx context.Context, id string) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PollID,
		&i.AuthorName,
		&i.ParticipantID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNotificationPref = `-- name: GetNotificationPref :one
SELECT user_id, channels, created_at, updated_at FROM notification_prefs WHERE user_id = $1
`

func (q *Queries) GetNotificationPref(ctx context.Context, userID int64) (NotificationPref, error) {
	row := q.db.QueryRowContext(ctx, getNotificationPref, userID)
	var i NotificationPref
	err := row.Scan(
		&i.UserID,
		&i.Channels,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationName = `-- name: GetOrganizationName :one
SELECT name FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationName(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getParticipant = `-- name: GetParticipant :one

SELECT id, poll_id, name, email, user_id, edit_token_hash, locale, created_at, updated_at FROM participants WHERE id = $1
`

// Task 3 (participants/votes/comments/claims) queries below.
func (q *Queries) GetParticipant(ctx context.Context, id string) (Participant, error) {
	row := q.db.QueryRowContext(ctx, getParticipant, id)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.PollID,
		&i.Name,
		&i.Email,
		&i.UserID,
		&i.EditTokenHash,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParticipantByPollAndUser = `-- name: GetParticipantByPollAndUser :one
SELECT id, poll_id, name, email, user_id, edit_token_hash, locale, created_at, updated_at FROM participants WHERE poll_id = $1 AND user_id = $2
`

type GetParticipantByPollAndUserParams struct {
	PollID string
	UserID sql.NullInt64
}

func (q *Queries) GetParticipantByPollAndUser(ctx context.Context, arg GetParticipantByPollAndUserParams) (Participant, error) {
	row := q.db.QueryRowContext(ctx, getParticipantByPollAndUser, arg.PollID, arg.UserID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.PollID,
		&i.Name,
		&i.Email,
		&i.UserID,
		&i.EditTokenHash,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParticipantForUpdate = `-- name: GetParticipantForUpdate :one
SELECT id, poll_id, name, email, user_id, edit_token_hash, locale, created_at, updated_at FROM participants WHERE id = $1 FOR UPDATE
`

// Locks the participant row for the duration of the enclosing transaction — Claim's second
// atomicity primitive, protecting a participant's own signupMaxClaims cap (see claims.go's Claim
// doc comment on lock ordering: option row first, then participant row, always in that order,
// everywhere): the SAME participant claiming two DIFFERENT options concurrently would otherwise
// each lock a different option row (no conflict there) and both read the same pre-claim count of
// existing votes, both pass the maxClaims check, and both insert — exceeding the cap. Locking the
// participant row before that count serializes concurrent claims by the same participant,
// regardless of which option each one targets.
func (q *Queries) GetParticipantForUpdate(ctx context.Context, id string) (Participant, error) {
	row := q.db.QueryRowContext(ctx, getParticipantForUpdate, id)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.PollID,
		&i.Name,
		&i.Email,
		&i.UserID,
		&i.EditTokenHash,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPoll = `-- name: GetPoll :one
SELECT id, organization_id, created_by, type, title, description, location, timezone, status, deadline_at, finalized_option_id, require_participant_email, allow_comments, allow_if_need_be, signup_max_claims, created_at, updated_at, deleted_at FROM polls WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPoll(ctx context.Context, id string) (Poll, error) {
	row := q.db.QueryRowContext(ctx, getPoll, id)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Timezone,
		&i.Status,
		&i.DeadlineAt,
		&i.FinalizedOptionID,
		&i.RequireParticipantEmail,
		&i.AllowComments,
		&i.AllowIfNeedBe,
		&i.SignupMaxClaims,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPollOptionForUpdate = `-- name: GetPollOptionForUpdate :one
SELECT id, poll_id, position, kind, start_at, end_at, label, capacity FROM poll_options WHERE id = $1 FOR UPDATE
`

// Locks the option row for the duration of the enclosing transaction — THE atomicity primitive
// Claim relies on (see claims.go's doc comment): every concurrent claimant on the same option
// blocks here until the transaction holding the lock commits or rolls back, so the capacity count
// taken after this line and the vote inserted before commit can never race with another claimant's
// count-then-insert on the same option.
func (q *Queries) GetPollOptionForUpdate(ctx context.Context, id string) (PollOption, error) {
	row := q.db.QueryRowContext(ctx, getPollOptionForUpdate, id)
	var i PollOption
	err := row.Scan(
		&i.ID,
		&i.PollID,
		&i.Position,
		&i.Kind,
		&i.StartAt,
		&i.EndAt,
		&i.Label,
		&i.Capacity,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT scope_type, scope_id, user_id, source, channels, created_at, updated_at FROM notification_subscriptions WHERE scope_type = $1 AND scope_id = $2 AND user_id = $3
`

type GetSubscriptionParams struct {
	ScopeType string
	ScopeID   string
	UserID    int64
}

// One viewer's own subscription row for one scope (buildView's per-viewer notifications block —
// getPollView, service.ts) — distinct from ListSubscriptionsByScope, which lists every
// subscriber and is used for mail fan-out (resolveRecipients), not a single viewer's own row.
func (q *Queries) GetSubscription(ctx context.Context, arg GetSubscriptionParams) (NotificationSubscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscription, arg.ScopeType, arg.ScopeID, arg.UserID)
	var i NotificationSubscription
	err := row.Scan(
		&i.ScopeType,
		&i.ScopeID,
		&i.UserID,
		&i.Source,
		&i.Channels,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one

SELECT id, email, password, email_verified_at, first_name, last_name, created_at, updated_at, two_factor_enabled FROM users WHERE id = $1
`

// Task 4 (notifications/finalize+claim mail/deadline+digest timers) queries below.
func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.EmailVerifiedAt,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TwoFactorEnabled,
	)
	return i, err
}

const insertComment = `-- name: InsertComment :exec
INSERT INTO comments (
  id, poll_id, author_name, participant_id, user_id, body, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
`

type InsertCommentParams struct {
	ID            string
	PollID        string
	AuthorName    string
	ParticipantID sql.NullString
	UserID        sql.NullInt64
	Body          string
	CreatedAt     time.Time
}

func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) error {
	_, err := q.db.ExecContext(ctx, insertComment,
		arg.ID,
		arg.PollID,
		arg.AuthorName,
		arg.ParticipantID,
		arg.UserID,
		arg.Body,
		arg.CreatedAt,
	)
	return err
}

const insertParticipant = `-- name: InsertParticipant :exec
INSERT INTO participants (
  id, poll_id, name, email, user_id, edit_token_hash, locale, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type InsertParticipantParams struct {
	ID            string
	PollID        string
	Name          string
	Email         sql.NullString
	UserID        sql.NullInt64
	EditTokenHash sql.NullString
	Locale        sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) InsertParticipant(ctx context.Context, arg InsertParticipantParams) error {
	_, err := q.db.ExecContext(ctx, insertParticipant,
		arg.ID,
		arg.PollID,
		arg.Name,
		arg.Email,
		arg.UserID,
		arg.EditTokenHash,
		arg.Locale,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertPoll = `-- name: InsertPoll :exec
INSERT INTO polls (
  id, organization_id, created_by, type, title, description, location, timezone,
  status, deadline_at, require_participant_email, allow_comments, allow_if_need_be,
  signup_max_claims, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
`

type InsertPollParams struct {
	ID                      string
	OrganizationID          int64
	CreatedBy               sql.NullInt64
	Type                    string
	Title                   string
	Description             sql.NullString
	Location                sql.NullString
	Timezone                string
	Status                  string
	DeadlineAt              sql.NullTime
	RequireParticipantEmail bool
	AllowComments           bool
	AllowIfNeedBe           bool
	SignupMaxClaims         int32
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

func (q *Queries) InsertPoll(ctx context.Context, arg InsertPollParams) error {
	_, err := q.db.ExecContext(ctx, insertPoll,
		arg.ID,
		arg.OrganizationID,
		arg.CreatedBy,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.Timezone,
		arg.Status,
		arg.DeadlineAt,
		arg.RequireParticipantEmail,
		arg.AllowComments,
		arg.AllowIfNeedBe,
		arg.SignupMaxClaims,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertPollOption = `-- name: InsertPollOption :exec
INSERT INTO poll_options (
  id, poll_id, position, kind, start_at, end_at, label, capacity
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertPollOptionParams struct {
	ID       string
	PollID   string
	Position int32
	Kind     string
	StartAt  sql.NullTime
	EndAt    sql.NullTime
	Label    sql.NullString
	Capacity sql.NullInt32
}

func (q *Queries) InsertPollOption(ctx context.Context, arg InsertPollOptionParams) error {
	_, err := q.db.ExecContext(ctx, insertPollOption,
		arg.ID,
		arg.PollID,
		arg.Position,
		arg.Kind,
		arg.StartAt,
		arg.EndAt,
		arg.Label,
		arg.Capacity,
	)
	return err
}

const isOrgMember = `-- name: IsOrgMember :one
SELECT EXISTS (
  SELECT 1 FROM organization_members WHERE organization_id = $1 AND user_id = $2
) AS is_member
`

type IsOrgMemberParams struct {
	OrganizationID int64
	UserID         int64
}

// Ports the membership-is-the-authority rule (recipients.ts): does userId still belong to
// organizationId at all, regardless of role? A subscription row surviving past someone leaving
// the org must not keep mailing them.
func (q *Queries) IsOrgMember(ctx context.Context, arg IsOrgMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isOrgMember, arg.OrganizationID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listCommentsByPoll = `-- name: ListCommentsByPoll :many
SELECT id, poll_id, author_name, participant_id, user_id, body, created_at, deleted_at FROM comments WHERE poll_id = $1 AND deleted_at IS NULL ORDER BY created_at
`

func (q *Queries) ListCommentsByPoll(ctx context.Context, pollID string) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByPoll, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PollID,
			&i.AuthorName,
			&i.ParticipantID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsByPoll = `-- name: ListOptionsByPoll :many
SELECT id, poll_id, position, kind, start_at, end_at, label, capacity FROM poll_options WHERE poll_id = $1 ORDER BY position
`

func (q *Queries) ListOptionsByPoll(ctx context.Context, pollID string) ([]PollOption, error) {
	rows, err := q.db.QueryContext(ctx, listOptionsByPoll, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PollOption
	for rows.Next() {
		var i PollOption
		if err := rows.Scan(
			&i.ID,
			&i.PollID,
			&i.Position,
			&i.Kind,
			&i.StartAt,
			&i.EndAt,
			&i.Label,
			&i.Capacity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantsByPoll = `-- name: ListParticipantsByPoll :many
SELECT id, poll_id, name, email, user_id, edit_token_hash, locale, created_at, updated_at FROM participants WHERE poll_id = $1 ORDER BY created_at
`

func (q *Queries) ListParticipantsByPoll(ctx context.Context, pollID string) ([]Participant, error) {
	rows, err := q.db.QueryContext(ctx, listParticipantsByPoll, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participant
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.PollID,
			&i.Name,
			&i.Email,
			&i.UserID,
			&i.EditTokenHash,
			&i.Locale,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPollsByOrg = `-- name: ListPollsByOrg :many
SELECT id, organization_id, created_by, type, title, description, location, timezone, status, deadline_at, finalized_option_id, require_participant_email, allow_comments, allow_if_need_be, signup_max_claims, created_at, updated_at, deleted_at FROM polls WHERE organization_id = $1 AND deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListPollsByOrg(ctx context.Context, organizationID int64) ([]Poll, error) {
	rows, err := q.db.QueryContext(ctx, listPollsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Poll
	for rows.Next() {
		var i Poll
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.Timezone,
			&i.Status,
			&i.DeadlineAt,
			&i.FinalizedOptionID,
			&i.RequireParticipantEmail,
			&i.AllowComments,
			&i.AllowIfNeedBe,
			&i.SignupMaxClaims,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByScope = `-- name: ListSubscriptionsByScope :many
SELECT scope_type, scope_id, user_id, source, channels, created_at, updated_at FROM notification_subscriptions WHERE scope_type = $1 AND scope_id = $2
`

type ListSubscriptionsByScopeParams struct {
	ScopeType string
	ScopeID   string
}

func (q *Queries) ListSubscriptionsByScope(ctx context.Context, arg ListSubscriptionsByScopeParams) ([]NotificationSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionsByScope, arg.ScopeType, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationSubscription
	for rows.Next() {
		var i NotificationSubscription
		if err := rows.Scan(
			&i.ScopeType,
			&i.ScopeID,
			&i.UserID,
			&i.Source,
			&i.Channels,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVotesByParticipant = `-- name: ListVotesByParticipant :many
SELECT participant_id, option_id, answer FROM votes WHERE participant_id = $1
`

func (q *Queries) ListVotesByParticipant(ctx context.Context, participantID string) ([]Vote, error) {
	rows, err := q.db.QueryContext(ctx, listVotesByParticipant, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vote
	for rows.Next() {
		var i Vote
		if err := rows.Scan(&i.ParticipantID, &i.OptionID, &i.Answer); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVotesByPoll = `-- name: ListVotesByPoll :many
SELECT v.participant_id, v.option_id, v.answer FROM votes v
JOIN participants p ON p.id = v.participant_id
WHERE p.poll_id = $1
`

func (q *Queries) ListVotesByPoll(ctx context.Context, pollID string) ([]Vote, error) {
	rows, err := q.db.QueryContext(ctx, listVotesByPoll, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vote
	for rows.Next() {
		var i Vote
		if err := rows.Scan(&i.ParticipantID, &i.OptionID, &i.Answer); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memberHasManagingRole = `-- name: MemberHasManagingRole :one
SELECT EXISTS (
  SELECT 1 FROM organization_members om
  JOIN organization_member_roles omr ON omr.member_id = om.id
  WHERE om.organization_id = $1 AND om.user_id = $2 AND omr.role IN ('owner', 'admin')
) AS has_role
`

type MemberHasManagingRoleParams struct {
	OrganizationID int64
	UserID         int64
}

// Ports canManageContent's role half (org-roles.ts): does userId hold an 'owner' or 'admin' role
// in organizationId? (The creator-manages-their-own-content half is checked separately by the
// caller against polls.created_by — this query only ever answers the role question.)
func (q *Queries) MemberHasManagingRole(ctx context.Context, arg MemberHasManagingRoleParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, memberHasManagingRole, arg.OrganizationID, arg.UserID)
	var has_role bool
	err := row.Scan(&has_role)
	return has_role, err
}

const pollExists = `-- name: PollExists :one
SELECT EXISTS(SELECT 1 FROM polls WHERE id = $1 AND deleted_at IS NULL)
`

func (q *Queries) PollExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, pollExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setNotificationSubscriptionChannels = `-- name: SetNotificationSubscriptionChannels :exec
UPDATE notification_subscriptions SET channels = $4::jsonb, updated_at = $5
WHERE scope_type = $1 AND scope_id = $2 AND user_id = $3
`

type SetNotificationSubscriptionChannelsParams struct {
	ScopeType string
	ScopeID   string
	UserID    int64
	Column4   json.RawMessage
	UpdatedAt time.Time
}

// $4 is NULL to clear an override back to the user's defaults (setScopeChannels's own doc
// comment in subscriptions.ts).
func (q *Queries) SetNotificationSubscriptionChannels(ctx context.Context, arg SetNotificationSubscriptionChannelsParams) error {
	_, err := q.db.ExecContext(ctx, setNotificationSubscriptionChannels,
		arg.ScopeType,
		arg.ScopeID,
		arg.UserID,
		arg.Column4,
		arg.UpdatedAt,
	)
	return err
}

const setPollStatus = `-- name: SetPollStatus :exec
UPDATE polls SET status = $2, updated_at = $3 WHERE id = $1
`

type SetPollStatusParams struct {
	ID        string
	Status    string
	UpdatedAt time.Time
}

func (q *Queries) SetPollStatus(ctx context.Context, arg SetPollStatusParams) error {
	_, err := q.db.ExecContext(ctx, setPollStatus, arg.ID, arg.Status, arg.UpdatedAt)
	return err
}

const softDeleteComment = `-- name: SoftDeleteComment :exec
UPDATE comments SET deleted_at = $3 WHERE id = $1 AND poll_id = $2
`

type SoftDeleteCommentParams struct {
	ID        string
	PollID    string
	DeletedAt sql.NullTime
}

func (q *Queries) SoftDeleteComment(ctx context.Context, arg SoftDeleteCommentParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteComment, arg.ID, arg.PollID, arg.DeletedAt)
	return err
}

const softDeletePoll = `-- name: SoftDeletePoll :exec
UPDATE polls SET deleted_at = $2, updated_at = $2 WHERE id = $1
`

type SoftDeletePollParams struct {
	ID        string
	DeletedAt sql.NullTime
}

func (q *Queries) SoftDeletePoll(ctx context.Context, arg SoftDeletePollParams) error {
	_, err := q.db.ExecContext(ctx, softDeletePoll, arg.ID, arg.DeletedAt)
	return err
}

const updateParticipantName = `-- name: UpdateParticipantName :exec
UPDATE participants SET name = $2, updated_at = $3 WHERE id = $1
`

type UpdateParticipantNameParams struct {
	ID        string
	Name      string
	UpdatedAt time.Time
}

func (q *Queries) UpdateParticipantName(ctx context.Context, arg UpdateParticipantNameParams) error {
	_, err := q.db.ExecContext(ctx, updateParticipantName, arg.ID, arg.Name, arg.UpdatedAt)
	return err
}

const updatePollOption = `-- name: UpdatePollOption :exec
UPDATE poll_options SET
  position = $2,
  kind = $3,
  start_at = $4,
  end_at = $5,
  label = $6,
  capacity = $7
WHERE id = $1
`

type UpdatePollOptionParams struct {
	ID       string
	Position int32
	Kind     string
	StartAt  sql.NullTime
	EndAt    sql.NullTime
	Label    sql.NullString
	Capacity sql.NullInt32
}

func (q *Queries) UpdatePollOption(ctx context.Context, arg UpdatePollOptionParams) error {
	_, err := q.db.ExecContext(ctx, updatePollOption,
		arg.ID,
		arg.Position,
		arg.Kind,
		arg.StartAt,
		arg.EndAt,
		arg.Label,
		arg.Capacity,
	)
	return err
}

const updatePollScalars = `-- name: UpdatePollScalars :exec
UPDATE polls SET
  title = $2,
  description = $3,
  location = $4,
  timezone = $5,
  deadline_at = $6,
  require_participant_email = $7,
  allow_comments = $8,
  allow_if_need_be = $9,
  signup_max_claims = $10,
  updated_at = $11
WHERE id = $1
`

type UpdatePollScalarsParams struct {
	ID                      string
	Title                   string
	Description             sql.NullString
	Location                sql.NullString
	Timezone                string
	DeadlineAt              sql.NullTime
	RequireParticipantEmail bool
	AllowComments           bool
	AllowIfNeedBe           bool
	SignupMaxClaims         int32
	UpdatedAt               time.Time
}

func (q *Queries) UpdatePollScalars(ctx context.Context, arg UpdatePollScalarsParams) error {
	_, err := q.db.ExecContext(ctx, updatePollScalars,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.Timezone,
		arg.DeadlineAt,
		arg.RequireParticipantEmail,
		arg.AllowComments,
		arg.AllowIfNeedBe,
		arg.SignupMaxClaims,
		arg.UpdatedAt,
	)
	return err
}

const upsertNotificationSubscription = `-- name: UpsertNotificationSubscription :exec
INSERT INTO notification_subscriptions (scope_type, scope_id, user_id, source, channels, created_at, updated_at)
VALUES ($1, $2, $3, $4, NULL, $5, $5)
ON CONFLICT (scope_type, scope_id, user_id) DO NOTHING
`

type UpsertNotificationSubscriptionParams struct {
	ScopeType string
	ScopeID   string
	UserID    int64
	Source    string
	CreatedAt time.Time
}

// Ports subscriptions.ts's upsert (ensureCreatorSubscription/followScope): a conflict on the
// (scope_type, scope_id, user_id) PK is a no-op, so re-following never resets an override the
// user already tuned.
func (q *Queries) UpsertNotificationSubscription(ctx context.Context, arg UpsertNotificationSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, upsertNotificationSubscription,
		arg.ScopeType,
		arg.ScopeID,
		arg.UserID,
		arg.Source,
		arg.CreatedAt,
	)
	return err
}

const upsertVote = `-- name: UpsertVote :exec
INSERT INTO votes (participant_id, option_id, answer)
VALUES ($1, $2, $3)
ON CONFLICT (participant_id, option_id) DO UPDATE SET answer = EXCLUDED.answer
`

type UpsertVoteParams struct {
	ParticipantID string
	OptionID      string
	Answer        string
}

func (q *Queries) UpsertVote(ctx context.Context, arg UpsertVoteParams) error {
	_, err := q.db.ExecContext(ctx, upsertVote, arg.ParticipantID, arg.OptionID, arg.Answer)
	return err
}
