// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: polls.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const finalizePoll = `-- name: FinalizePoll :exec
UPDATE polls SET finalized_option_id = $2, status = $3, updated_at = $4 WHERE id = $1
`

type FinalizePollParams struct {
	ID                string
	FinalizedOptionID sql.NullString
	Status            string
	UpdatedAt         time.Time
}

func (q *Queries) FinalizePoll(ctx context.Context, arg FinalizePollParams) error {
	_, err := q.db.ExecContext(ctx, finalizePoll,
		arg.ID,
		arg.FinalizedOptionID,
		arg.Status,
		arg.UpdatedAt,
	)
	return err
}

const getPoll = `-- name: GetPoll :one
SELECT id, organization_id, created_by, type, title, description, location, timezone, status, deadline_at, finalized_option_id, require_participant_email, allow_comments, allow_if_need_be, signup_max_claims, created_at, updated_at, deleted_at FROM polls WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPoll(ctx context.Context, id string) (Poll, error) {
	row := q.db.QueryRowContext(ctx, getPoll, id)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Timezone,
		&i.Status,
		&i.DeadlineAt,
		&i.FinalizedOptionID,
		&i.RequireParticipantEmail,
		&i.AllowComments,
		&i.AllowIfNeedBe,
		&i.SignupMaxClaims,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertComment = `-- name: InsertComment :exec
INSERT INTO comments (
  id, poll_id, author_name, participant_id, user_id, body, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
`

type InsertCommentParams struct {
	ID            string
	PollID        string
	AuthorName    string
	ParticipantID sql.NullString
	UserID        sql.NullInt64
	Body          string
	CreatedAt     time.Time
}

func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) error {
	_, err := q.db.ExecContext(ctx, insertComment,
		arg.ID,
		arg.PollID,
		arg.AuthorName,
		arg.ParticipantID,
		arg.UserID,
		arg.Body,
		arg.CreatedAt,
	)
	return err
}

const insertParticipant = `-- name: InsertParticipant :exec
INSERT INTO participants (
  id, poll_id, name, email, user_id, edit_token_hash, locale, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type InsertParticipantParams struct {
	ID            string
	PollID        string
	Name          string
	Email         sql.NullString
	UserID        sql.NullInt64
	EditTokenHash sql.NullString
	Locale        sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) InsertParticipant(ctx context.Context, arg InsertParticipantParams) error {
	_, err := q.db.ExecContext(ctx, insertParticipant,
		arg.ID,
		arg.PollID,
		arg.Name,
		arg.Email,
		arg.UserID,
		arg.EditTokenHash,
		arg.Locale,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertPoll = `-- name: InsertPoll :exec
INSERT INTO polls (
  id, organization_id, created_by, type, title, description, location, timezone,
  status, deadline_at, require_participant_email, allow_comments, allow_if_need_be,
  signup_max_claims, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
`

type InsertPollParams struct {
	ID                      string
	OrganizationID          int64
	CreatedBy               sql.NullInt64
	Type                    string
	Title                   string
	Description             sql.NullString
	Location                sql.NullString
	Timezone                string
	Status                  string
	DeadlineAt              sql.NullTime
	RequireParticipantEmail bool
	AllowComments           bool
	AllowIfNeedBe           bool
	SignupMaxClaims         int32
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

func (q *Queries) InsertPoll(ctx context.Context, arg InsertPollParams) error {
	_, err := q.db.ExecContext(ctx, insertPoll,
		arg.ID,
		arg.OrganizationID,
		arg.CreatedBy,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.Timezone,
		arg.Status,
		arg.DeadlineAt,
		arg.RequireParticipantEmail,
		arg.AllowComments,
		arg.AllowIfNeedBe,
		arg.SignupMaxClaims,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertPollOption = `-- name: InsertPollOption :exec
INSERT INTO poll_options (
  id, poll_id, position, kind, start_at, end_at, label, capacity
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertPollOptionParams struct {
	ID       string
	PollID   string
	Position int32
	Kind     string
	StartAt  sql.NullTime
	EndAt    sql.NullTime
	Label    sql.NullString
	Capacity sql.NullInt32
}

func (q *Queries) InsertPollOption(ctx context.Context, arg InsertPollOptionParams) error {
	_, err := q.db.ExecContext(ctx, insertPollOption,
		arg.ID,
		arg.PollID,
		arg.Position,
		arg.Kind,
		arg.StartAt,
		arg.EndAt,
		arg.Label,
		arg.Capacity,
	)
	return err
}

const listCommentsByPoll = `-- name: ListCommentsByPoll :many
SELECT id, poll_id, author_name, participant_id, user_id, body, created_at, deleted_at FROM comments WHERE poll_id = $1 AND deleted_at IS NULL ORDER BY created_at
`

func (q *Queries) ListCommentsByPoll(ctx context.Context, pollID string) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByPoll, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PollID,
			&i.AuthorName,
			&i.ParticipantID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsByPoll = `-- name: ListOptionsByPoll :many
SELECT id, poll_id, position, kind, start_at, end_at, label, capacity FROM poll_options WHERE poll_id = $1 ORDER BY position
`

func (q *Queries) ListOptionsByPoll(ctx context.Context, pollID string) ([]PollOption, error) {
	rows, err := q.db.QueryContext(ctx, listOptionsByPoll, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PollOption
	for rows.Next() {
		var i PollOption
		if err := rows.Scan(
			&i.ID,
			&i.PollID,
			&i.Position,
			&i.Kind,
			&i.StartAt,
			&i.EndAt,
			&i.Label,
			&i.Capacity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantsByPoll = `-- name: ListParticipantsByPoll :many
SELECT id, poll_id, name, email, user_id, edit_token_hash, locale, created_at, updated_at FROM participants WHERE poll_id = $1 ORDER BY created_at
`

func (q *Queries) ListParticipantsByPoll(ctx context.Context, pollID string) ([]Participant, error) {
	rows, err := q.db.QueryContext(ctx, listParticipantsByPoll, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participant
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.PollID,
			&i.Name,
			&i.Email,
			&i.UserID,
			&i.EditTokenHash,
			&i.Locale,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPollsByOrg = `-- name: ListPollsByOrg :many
SELECT id, organization_id, created_by, type, title, description, location, timezone, status, deadline_at, finalized_option_id, require_participant_email, allow_comments, allow_if_need_be, signup_max_claims, created_at, updated_at, deleted_at FROM polls WHERE organization_id = $1 AND deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListPollsByOrg(ctx context.Context, organizationID int64) ([]Poll, error) {
	rows, err := q.db.QueryContext(ctx, listPollsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Poll
	for rows.Next() {
		var i Poll
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.Timezone,
			&i.Status,
			&i.DeadlineAt,
			&i.FinalizedOptionID,
			&i.RequireParticipantEmail,
			&i.AllowComments,
			&i.AllowIfNeedBe,
			&i.SignupMaxClaims,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVotesByPoll = `-- name: ListVotesByPoll :many
SELECT v.participant_id, v.option_id, v.answer FROM votes v
JOIN participants p ON p.id = v.participant_id
WHERE p.poll_id = $1
`

func (q *Queries) ListVotesByPoll(ctx context.Context, pollID string) ([]Vote, error) {
	rows, err := q.db.QueryContext(ctx, listVotesByPoll, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vote
	for rows.Next() {
		var i Vote
		if err := rows.Scan(&i.ParticipantID, &i.OptionID, &i.Answer); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPollStatus = `-- name: SetPollStatus :exec
UPDATE polls SET status = $2, updated_at = $3 WHERE id = $1
`

type SetPollStatusParams struct {
	ID        string
	Status    string
	UpdatedAt time.Time
}

func (q *Queries) SetPollStatus(ctx context.Context, arg SetPollStatusParams) error {
	_, err := q.db.ExecContext(ctx, setPollStatus, arg.ID, arg.Status, arg.UpdatedAt)
	return err
}

const softDeletePoll = `-- name: SoftDeletePoll :exec
UPDATE polls SET deleted_at = $2, updated_at = $2 WHERE id = $1
`

type SoftDeletePollParams struct {
	ID        string
	DeletedAt sql.NullTime
}

func (q *Queries) SoftDeletePoll(ctx context.Context, arg SoftDeletePollParams) error {
	_, err := q.db.ExecContext(ctx, softDeletePoll, arg.ID, arg.DeletedAt)
	return err
}

const upsertVote = `-- name: UpsertVote :exec
INSERT INTO votes (participant_id, option_id, answer)
VALUES ($1, $2, $3)
ON CONFLICT (participant_id, option_id) DO UPDATE SET answer = EXCLUDED.answer
`

type UpsertVoteParams struct {
	ParticipantID string
	OptionID      string
	Answer        string
}

func (q *Queries) UpsertVote(ctx context.Context, arg UpsertVoteParams) error {
	_, err := q.db.ExecContext(ctx, upsertVote, arg.ParticipantID, arg.OptionID, arg.Answer)
	return err
}
