// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"
)

type Querier interface {
	DeletePollOption(ctx context.Context, id string) error
	FinalizePoll(ctx context.Context, arg FinalizePollParams) error
	GetOrganizationName(ctx context.Context, id int64) (string, error)
	GetPoll(ctx context.Context, id string) (Poll, error)
	InsertComment(ctx context.Context, arg InsertCommentParams) error
	InsertParticipant(ctx context.Context, arg InsertParticipantParams) error
	InsertPoll(ctx context.Context, arg InsertPollParams) error
	InsertPollOption(ctx context.Context, arg InsertPollOptionParams) error
	ListCommentsByPoll(ctx context.Context, pollID string) ([]Comment, error)
	ListOptionsByPoll(ctx context.Context, pollID string) ([]PollOption, error)
	ListParticipantsByPoll(ctx context.Context, pollID string) ([]Participant, error)
	ListPollsByOrg(ctx context.Context, organizationID int64) ([]Poll, error)
	ListVotesByPoll(ctx context.Context, pollID string) ([]Vote, error)
	SetPollStatus(ctx context.Context, arg SetPollStatusParams) error
	SoftDeletePoll(ctx context.Context, arg SoftDeletePollParams) error
	UpdatePollOption(ctx context.Context, arg UpdatePollOptionParams) error
	UpdatePollScalars(ctx context.Context, arg UpdatePollScalarsParams) error
	UpsertVote(ctx context.Context, arg UpsertVoteParams) error
}

var _ Querier = (*Queries)(nil)
