/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTestSeedRouteImport } from './routes/api/test/seed'
import { Route as PIdCalendarDoticsRouteImport } from './routes/p/$id/calendar[.]ics'
import { Route as ApiPollsIdWsRouteImport } from './routes/api/polls/$id/ws'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestSeedRoute = ApiTestSeedRouteImport.update({
  id: '/api/test/seed',
  path: '/api/test/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdCalendarDoticsRoute = PIdCalendarDoticsRouteImport.update({
  id: '/p/$id/calendar.ics',
  path: '/p/$id/calendar.ics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPollsIdWsRoute = ApiPollsIdWsRouteImport.update({
  id: '/api/polls/$id/ws',
  path: '/api/polls/$id/ws',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/test/seed': typeof ApiTestSeedRoute
  '/p/$id/calendar.ics': typeof PIdCalendarDoticsRoute
  '/api/polls/$id/ws': typeof ApiPollsIdWsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/test/seed': typeof ApiTestSeedRoute
  '/p/$id/calendar.ics': typeof PIdCalendarDoticsRoute
  '/api/polls/$id/ws': typeof ApiPollsIdWsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/test/seed': typeof ApiTestSeedRoute
  '/p/$id/calendar.ics': typeof PIdCalendarDoticsRoute
  '/api/polls/$id/ws': typeof ApiPollsIdWsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/new'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/api/auth/$'
    | '/api/test/seed'
    | '/p/$id/calendar.ics'
    | '/api/polls/$id/ws'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/new'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/api/auth/$'
    | '/api/test/seed'
    | '/p/$id/calendar.ics'
    | '/api/polls/$id/ws'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/new'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/api/auth/$'
    | '/api/test/seed'
    | '/p/$id/calendar.ics'
    | '/api/polls/$id/ws'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTestSeedRoute: typeof ApiTestSeedRoute
  PIdCalendarDoticsRoute: typeof PIdCalendarDoticsRoute
  ApiPollsIdWsRoute: typeof ApiPollsIdWsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/seed': {
      id: '/api/test/seed'
      path: '/api/test/seed'
      fullPath: '/api/test/seed'
      preLoaderRoute: typeof ApiTestSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id/calendar.ics': {
      id: '/p/$id/calendar.ics'
      path: '/p/$id/calendar.ics'
      fullPath: '/p/$id/calendar.ics'
      preLoaderRoute: typeof PIdCalendarDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polls/$id/ws': {
      id: '/api/polls/$id/ws'
      path: '/api/polls/$id/ws'
      fullPath: '/api/polls/$id/ws'
      preLoaderRoute: typeof ApiPollsIdWsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTestSeedRoute: ApiTestSeedRoute,
  PIdCalendarDoticsRoute: PIdCalendarDoticsRoute,
  ApiPollsIdWsRoute: ApiPollsIdWsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
