/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as BookingsIndexRouteImport } from './routes/bookings/index'
import { Route as BookingsNewRouteImport } from './routes/bookings/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTestSeedRouteImport } from './routes/api/test/seed'
import { Route as BookingIdCalendarDoticsRouteImport } from './routes/booking/$id/calendar[.]ics'
import { Route as BookingsIdIndexRouteImport } from './routes/bookings/$id/index'
import { Route as BookingsIdEditRouteImport } from './routes/bookings/$id/edit'
import { Route as PIdIndexRouteImport } from './routes/p/$id/index'
import { Route as PIdCalendarDoticsRouteImport } from './routes/p/$id/calendar[.]ics'
import { Route as PIdEditRouteImport } from './routes/p/$id/edit'
import { Route as PIdRosterDotcsvRouteImport } from './routes/p/$id/roster[.]csv'
import { Route as ApiBookingsPageIdWsRouteImport } from './routes/api/bookings/$pageId/ws'
import { Route as ApiPollsIdWsRouteImport } from './routes/api/polls/$id/ws'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsNewRoute = BookingsNewRouteImport.update({
  id: '/bookings/new',
  path: '/bookings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestSeedRoute = ApiTestSeedRouteImport.update({
  id: '/api/test/seed',
  path: '/api/test/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdCalendarDoticsRoute = BookingIdCalendarDoticsRouteImport.update({
  id: '/booking/$id/calendar.ics',
  path: '/booking/$id/calendar.ics',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdIndexRoute = BookingsIdIndexRouteImport.update({
  id: '/bookings/$id/',
  path: '/bookings/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdEditRoute = BookingsIdEditRouteImport.update({
  id: '/bookings/$id/edit',
  path: '/bookings/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdIndexRoute = PIdIndexRouteImport.update({
  id: '/p/$id/',
  path: '/p/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdCalendarDoticsRoute = PIdCalendarDoticsRouteImport.update({
  id: '/p/$id/calendar.ics',
  path: '/p/$id/calendar.ics',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdEditRoute = PIdEditRouteImport.update({
  id: '/p/$id/edit',
  path: '/p/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRosterDotcsvRoute = PIdRosterDotcsvRouteImport.update({
  id: '/p/$id/roster.csv',
  path: '/p/$id/roster.csv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsPageIdWsRoute = ApiBookingsPageIdWsRouteImport.update({
  id: '/api/bookings/$pageId/ws',
  path: '/api/bookings/$pageId/ws',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPollsIdWsRoute = ApiPollsIdWsRouteImport.update({
  id: '/api/polls/$id/ws',
  path: '/api/polls/$id/ws',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/bookings/new': typeof BookingsNewRoute
  '/bookings/': typeof BookingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/test/seed': typeof ApiTestSeedRoute
  '/booking/$id/calendar.ics': typeof BookingIdCalendarDoticsRoute
  '/bookings/$id/edit': typeof BookingsIdEditRoute
  '/p/$id/calendar.ics': typeof PIdCalendarDoticsRoute
  '/p/$id/edit': typeof PIdEditRoute
  '/p/$id/roster.csv': typeof PIdRosterDotcsvRoute
  '/bookings/$id/': typeof BookingsIdIndexRoute
  '/p/$id/': typeof PIdIndexRoute
  '/api/bookings/$pageId/ws': typeof ApiBookingsPageIdWsRoute
  '/api/polls/$id/ws': typeof ApiPollsIdWsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/bookings/new': typeof BookingsNewRoute
  '/bookings': typeof BookingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/test/seed': typeof ApiTestSeedRoute
  '/booking/$id/calendar.ics': typeof BookingIdCalendarDoticsRoute
  '/bookings/$id/edit': typeof BookingsIdEditRoute
  '/p/$id/calendar.ics': typeof PIdCalendarDoticsRoute
  '/p/$id/edit': typeof PIdEditRoute
  '/p/$id/roster.csv': typeof PIdRosterDotcsvRoute
  '/bookings/$id': typeof BookingsIdIndexRoute
  '/p/$id': typeof PIdIndexRoute
  '/api/bookings/$pageId/ws': typeof ApiBookingsPageIdWsRoute
  '/api/polls/$id/ws': typeof ApiPollsIdWsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/bookings/new': typeof BookingsNewRoute
  '/bookings/': typeof BookingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/test/seed': typeof ApiTestSeedRoute
  '/booking/$id/calendar.ics': typeof BookingIdCalendarDoticsRoute
  '/bookings/$id/edit': typeof BookingsIdEditRoute
  '/p/$id/calendar.ics': typeof PIdCalendarDoticsRoute
  '/p/$id/edit': typeof PIdEditRoute
  '/p/$id/roster.csv': typeof PIdRosterDotcsvRoute
  '/bookings/$id/': typeof BookingsIdIndexRoute
  '/p/$id/': typeof PIdIndexRoute
  '/api/bookings/$pageId/ws': typeof ApiBookingsPageIdWsRoute
  '/api/polls/$id/ws': typeof ApiPollsIdWsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/new'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/bookings/new'
    | '/bookings/'
    | '/api/auth/$'
    | '/api/test/seed'
    | '/booking/$id/calendar.ics'
    | '/bookings/$id/edit'
    | '/p/$id/calendar.ics'
    | '/p/$id/edit'
    | '/p/$id/roster.csv'
    | '/bookings/$id/'
    | '/p/$id/'
    | '/api/bookings/$pageId/ws'
    | '/api/polls/$id/ws'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/new'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/bookings/new'
    | '/bookings'
    | '/api/auth/$'
    | '/api/test/seed'
    | '/booking/$id/calendar.ics'
    | '/bookings/$id/edit'
    | '/p/$id/calendar.ics'
    | '/p/$id/edit'
    | '/p/$id/roster.csv'
    | '/bookings/$id'
    | '/p/$id'
    | '/api/bookings/$pageId/ws'
    | '/api/polls/$id/ws'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/new'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/bookings/new'
    | '/bookings/'
    | '/api/auth/$'
    | '/api/test/seed'
    | '/booking/$id/calendar.ics'
    | '/bookings/$id/edit'
    | '/p/$id/calendar.ics'
    | '/p/$id/edit'
    | '/p/$id/roster.csv'
    | '/bookings/$id/'
    | '/p/$id/'
    | '/api/bookings/$pageId/ws'
    | '/api/polls/$id/ws'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  BookingsNewRoute: typeof BookingsNewRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTestSeedRoute: typeof ApiTestSeedRoute
  BookingIdCalendarDoticsRoute: typeof BookingIdCalendarDoticsRoute
  BookingsIdEditRoute: typeof BookingsIdEditRoute
  PIdCalendarDoticsRoute: typeof PIdCalendarDoticsRoute
  PIdEditRoute: typeof PIdEditRoute
  PIdRosterDotcsvRoute: typeof PIdRosterDotcsvRoute
  BookingsIdIndexRoute: typeof BookingsIdIndexRoute
  PIdIndexRoute: typeof PIdIndexRoute
  ApiBookingsPageIdWsRoute: typeof ApiBookingsPageIdWsRoute
  ApiPollsIdWsRoute: typeof ApiPollsIdWsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/new': {
      id: '/bookings/new'
      path: '/bookings/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof BookingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/seed': {
      id: '/api/test/seed'
      path: '/api/test/seed'
      fullPath: '/api/test/seed'
      preLoaderRoute: typeof ApiTestSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id/calendar.ics': {
      id: '/booking/$id/calendar.ics'
      path: '/booking/$id/calendar.ics'
      fullPath: '/booking/$id/calendar.ics'
      preLoaderRoute: typeof BookingIdCalendarDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id/': {
      id: '/bookings/$id/'
      path: '/bookings/$id'
      fullPath: '/bookings/$id/'
      preLoaderRoute: typeof BookingsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id/edit': {
      id: '/bookings/$id/edit'
      path: '/bookings/$id/edit'
      fullPath: '/bookings/$id/edit'
      preLoaderRoute: typeof BookingsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id/': {
      id: '/p/$id/'
      path: '/p/$id'
      fullPath: '/p/$id/'
      preLoaderRoute: typeof PIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id/calendar.ics': {
      id: '/p/$id/calendar.ics'
      path: '/p/$id/calendar.ics'
      fullPath: '/p/$id/calendar.ics'
      preLoaderRoute: typeof PIdCalendarDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id/edit': {
      id: '/p/$id/edit'
      path: '/p/$id/edit'
      fullPath: '/p/$id/edit'
      preLoaderRoute: typeof PIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id/roster.csv': {
      id: '/p/$id/roster.csv'
      path: '/p/$id/roster.csv'
      fullPath: '/p/$id/roster.csv'
      preLoaderRoute: typeof PIdRosterDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings/$pageId/ws': {
      id: '/api/bookings/$pageId/ws'
      path: '/api/bookings/$pageId/ws'
      fullPath: '/api/bookings/$pageId/ws'
      preLoaderRoute: typeof ApiBookingsPageIdWsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polls/$id/ws': {
      id: '/api/polls/$id/ws'
      path: '/api/polls/$id/ws'
      fullPath: '/api/polls/$id/ws'
      preLoaderRoute: typeof ApiPollsIdWsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  BookingsNewRoute: BookingsNewRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTestSeedRoute: ApiTestSeedRoute,
  BookingIdCalendarDoticsRoute: BookingIdCalendarDoticsRoute,
  BookingsIdEditRoute: BookingsIdEditRoute,
  PIdCalendarDoticsRoute: PIdCalendarDoticsRoute,
  PIdEditRoute: PIdEditRoute,
  PIdRosterDotcsvRoute: PIdRosterDotcsvRoute,
  BookingsIdIndexRoute: BookingsIdIndexRoute,
  PIdIndexRoute: PIdIndexRoute,
  ApiBookingsPageIdWsRoute: ApiBookingsPageIdWsRoute,
  ApiPollsIdWsRoute: ApiPollsIdWsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
