/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AcceptInvitationIdRouteImport } from './routes/accept-invitation/$id'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as BookingsIndexRouteImport } from './routes/bookings/index'
import { Route as BookingsNewRouteImport } from './routes/bookings/new'
import { Route as AdminUsersIdRouteImport } from './routes/admin/users.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStatsWsRouteImport } from './routes/api/stats/ws'
import { Route as ApiTestSeedRouteImport } from './routes/api/test/seed'
import { Route as BookHandleSlugRouteImport } from './routes/book/$handle/$slug'
import { Route as BookingIdIndexRouteImport } from './routes/booking/$id/index'
import { Route as BookingIdCalendarDoticsRouteImport } from './routes/booking/$id/calendar[.]ics'
import { Route as BookingsIdIndexRouteImport } from './routes/bookings/$id/index'
import { Route as BookingsIdEditRouteImport } from './routes/bookings/$id/edit'
import { Route as PIdIndexRouteImport } from './routes/p/$id/index'
import { Route as PIdCalendarDoticsRouteImport } from './routes/p/$id/calendar[.]ics'
import { Route as PIdEditRouteImport } from './routes/p/$id/edit'
import { Route as PIdRosterDotcsvRouteImport } from './routes/p/$id/roster[.]csv'
import { Route as ApiBookingsPageIdWsRouteImport } from './routes/api/bookings/$pageId/ws'
import { Route as ApiPollsIdWsRouteImport } from './routes/api/polls/$id/ws'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationIdRoute = AcceptInvitationIdRouteImport.update({
  id: '/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsNewRoute = BookingsNewRouteImport.update({
  id: '/bookings/new',
  path: '/bookings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsWsRoute = ApiStatsWsRouteImport.update({
  id: '/api/stats/ws',
  path: '/api/stats/ws',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestSeedRoute = ApiTestSeedRouteImport.update({
  id: '/api/test/seed',
  path: '/api/test/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const BookHandleSlugRoute = BookHandleSlugRouteImport.update({
  id: '/book/$handle/$slug',
  path: '/book/$handle/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdIndexRoute = BookingIdIndexRouteImport.update({
  id: '/booking/$id/',
  path: '/booking/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdCalendarDoticsRoute = BookingIdCalendarDoticsRouteImport.update({
  id: '/booking/$id/calendar.ics',
  path: '/booking/$id/calendar.ics',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdIndexRoute = BookingsIdIndexRouteImport.update({
  id: '/bookings/$id/',
  path: '/bookings/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdEditRoute = BookingsIdEditRouteImport.update({
  id: '/bookings/$id/edit',
  path: '/bookings/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdIndexRoute = PIdIndexRouteImport.update({
  id: '/p/$id/',
  path: '/p/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdCalendarDoticsRoute = PIdCalendarDoticsRouteImport.update({
  id: '/p/$id/calendar.ics',
  path: '/p/$id/calendar.ics',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdEditRoute = PIdEditRouteImport.update({
  id: '/p/$id/edit',
  path: '/p/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRosterDotcsvRoute = PIdRosterDotcsvRouteImport.update({
  id: '/p/$id/roster.csv',
  path: '/p/$id/roster.csv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsPageIdWsRoute = ApiBookingsPageIdWsRouteImport.update({
  id: '/api/bookings/$pageId/ws',
  path: '/api/bookings/$pageId/ws',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPollsIdWsRoute = ApiPollsIdWsRouteImport.update({
  id: '/api/polls/$id/ws',
  path: '/api/polls/$id/ws',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/bookings/new': typeof BookingsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stats/ws': typeof ApiStatsWsRoute
  '/api/test/seed': typeof ApiTestSeedRoute
  '/book/$handle/$slug': typeof BookHandleSlugRoute
  '/booking/$id/calendar.ics': typeof BookingIdCalendarDoticsRoute
  '/bookings/$id/edit': typeof BookingsIdEditRoute
  '/p/$id/calendar.ics': typeof PIdCalendarDoticsRoute
  '/p/$id/edit': typeof PIdEditRoute
  '/p/$id/roster.csv': typeof PIdRosterDotcsvRoute
  '/booking/$id/': typeof BookingIdIndexRoute
  '/bookings/$id/': typeof BookingsIdIndexRoute
  '/p/$id/': typeof PIdIndexRoute
  '/api/bookings/$pageId/ws': typeof ApiBookingsPageIdWsRoute
  '/api/polls/$id/ws': typeof ApiPollsIdWsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/bookings/new': typeof BookingsNewRoute
  '/admin': typeof AdminIndexRoute
  '/bookings': typeof BookingsIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stats/ws': typeof ApiStatsWsRoute
  '/api/test/seed': typeof ApiTestSeedRoute
  '/book/$handle/$slug': typeof BookHandleSlugRoute
  '/booking/$id/calendar.ics': typeof BookingIdCalendarDoticsRoute
  '/bookings/$id/edit': typeof BookingsIdEditRoute
  '/p/$id/calendar.ics': typeof PIdCalendarDoticsRoute
  '/p/$id/edit': typeof PIdEditRoute
  '/p/$id/roster.csv': typeof PIdRosterDotcsvRoute
  '/booking/$id': typeof BookingIdIndexRoute
  '/bookings/$id': typeof BookingsIdIndexRoute
  '/p/$id': typeof PIdIndexRoute
  '/api/bookings/$pageId/ws': typeof ApiBookingsPageIdWsRoute
  '/api/polls/$id/ws': typeof ApiPollsIdWsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/bookings/new': typeof BookingsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stats/ws': typeof ApiStatsWsRoute
  '/api/test/seed': typeof ApiTestSeedRoute
  '/book/$handle/$slug': typeof BookHandleSlugRoute
  '/booking/$id/calendar.ics': typeof BookingIdCalendarDoticsRoute
  '/bookings/$id/edit': typeof BookingsIdEditRoute
  '/p/$id/calendar.ics': typeof PIdCalendarDoticsRoute
  '/p/$id/edit': typeof PIdEditRoute
  '/p/$id/roster.csv': typeof PIdRosterDotcsvRoute
  '/booking/$id/': typeof BookingIdIndexRoute
  '/bookings/$id/': typeof BookingsIdIndexRoute
  '/p/$id/': typeof PIdIndexRoute
  '/api/bookings/$pageId/ws': typeof ApiBookingsPageIdWsRoute
  '/api/polls/$id/ws': typeof ApiPollsIdWsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/new'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/accept-invitation/$id'
    | '/admin/audit'
    | '/admin/users'
    | '/api/health'
    | '/bookings/new'
    | '/admin/'
    | '/bookings/'
    | '/admin/users/$id'
    | '/api/auth/$'
    | '/api/stats/ws'
    | '/api/test/seed'
    | '/book/$handle/$slug'
    | '/booking/$id/calendar.ics'
    | '/bookings/$id/edit'
    | '/p/$id/calendar.ics'
    | '/p/$id/edit'
    | '/p/$id/roster.csv'
    | '/booking/$id/'
    | '/bookings/$id/'
    | '/p/$id/'
    | '/api/bookings/$pageId/ws'
    | '/api/polls/$id/ws'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/new'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/accept-invitation/$id'
    | '/admin/audit'
    | '/admin/users'
    | '/api/health'
    | '/bookings/new'
    | '/admin'
    | '/bookings'
    | '/admin/users/$id'
    | '/api/auth/$'
    | '/api/stats/ws'
    | '/api/test/seed'
    | '/book/$handle/$slug'
    | '/booking/$id/calendar.ics'
    | '/bookings/$id/edit'
    | '/p/$id/calendar.ics'
    | '/p/$id/edit'
    | '/p/$id/roster.csv'
    | '/booking/$id'
    | '/bookings/$id'
    | '/p/$id'
    | '/api/bookings/$pageId/ws'
    | '/api/polls/$id/ws'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/new'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/accept-invitation/$id'
    | '/admin/audit'
    | '/admin/users'
    | '/api/health'
    | '/bookings/new'
    | '/admin/'
    | '/bookings/'
    | '/admin/users/$id'
    | '/api/auth/$'
    | '/api/stats/ws'
    | '/api/test/seed'
    | '/book/$handle/$slug'
    | '/booking/$id/calendar.ics'
    | '/bookings/$id/edit'
    | '/p/$id/calendar.ics'
    | '/p/$id/edit'
    | '/p/$id/roster.csv'
    | '/booking/$id/'
    | '/bookings/$id/'
    | '/p/$id/'
    | '/api/bookings/$pageId/ws'
    | '/api/polls/$id/ws'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AcceptInvitationIdRoute: typeof AcceptInvitationIdRoute
  ApiHealthRoute: typeof ApiHealthRoute
  BookingsNewRoute: typeof BookingsNewRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStatsWsRoute: typeof ApiStatsWsRoute
  ApiTestSeedRoute: typeof ApiTestSeedRoute
  BookHandleSlugRoute: typeof BookHandleSlugRoute
  BookingIdCalendarDoticsRoute: typeof BookingIdCalendarDoticsRoute
  BookingsIdEditRoute: typeof BookingsIdEditRoute
  PIdCalendarDoticsRoute: typeof PIdCalendarDoticsRoute
  PIdEditRoute: typeof PIdEditRoute
  PIdRosterDotcsvRoute: typeof PIdRosterDotcsvRoute
  BookingIdIndexRoute: typeof BookingIdIndexRoute
  BookingsIdIndexRoute: typeof BookingsIdIndexRoute
  PIdIndexRoute: typeof PIdIndexRoute
  ApiBookingsPageIdWsRoute: typeof ApiBookingsPageIdWsRoute
  ApiPollsIdWsRoute: typeof ApiPollsIdWsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$id': {
      id: '/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof AcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/new': {
      id: '/bookings/new'
      path: '/bookings/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof BookingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats/ws': {
      id: '/api/stats/ws'
      path: '/api/stats/ws'
      fullPath: '/api/stats/ws'
      preLoaderRoute: typeof ApiStatsWsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/seed': {
      id: '/api/test/seed'
      path: '/api/test/seed'
      fullPath: '/api/test/seed'
      preLoaderRoute: typeof ApiTestSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$handle/$slug': {
      id: '/book/$handle/$slug'
      path: '/book/$handle/$slug'
      fullPath: '/book/$handle/$slug'
      preLoaderRoute: typeof BookHandleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id/': {
      id: '/booking/$id/'
      path: '/booking/$id'
      fullPath: '/booking/$id/'
      preLoaderRoute: typeof BookingIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id/calendar.ics': {
      id: '/booking/$id/calendar.ics'
      path: '/booking/$id/calendar.ics'
      fullPath: '/booking/$id/calendar.ics'
      preLoaderRoute: typeof BookingIdCalendarDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id/': {
      id: '/bookings/$id/'
      path: '/bookings/$id'
      fullPath: '/bookings/$id/'
      preLoaderRoute: typeof BookingsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id/edit': {
      id: '/bookings/$id/edit'
      path: '/bookings/$id/edit'
      fullPath: '/bookings/$id/edit'
      preLoaderRoute: typeof BookingsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id/': {
      id: '/p/$id/'
      path: '/p/$id'
      fullPath: '/p/$id/'
      preLoaderRoute: typeof PIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id/calendar.ics': {
      id: '/p/$id/calendar.ics'
      path: '/p/$id/calendar.ics'
      fullPath: '/p/$id/calendar.ics'
      preLoaderRoute: typeof PIdCalendarDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id/edit': {
      id: '/p/$id/edit'
      path: '/p/$id/edit'
      fullPath: '/p/$id/edit'
      preLoaderRoute: typeof PIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id/roster.csv': {
      id: '/p/$id/roster.csv'
      path: '/p/$id/roster.csv'
      fullPath: '/p/$id/roster.csv'
      preLoaderRoute: typeof PIdRosterDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings/$pageId/ws': {
      id: '/api/bookings/$pageId/ws'
      path: '/api/bookings/$pageId/ws'
      fullPath: '/api/bookings/$pageId/ws'
      preLoaderRoute: typeof ApiBookingsPageIdWsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polls/$id/ws': {
      id: '/api/polls/$id/ws'
      path: '/api/polls/$id/ws'
      fullPath: '/api/polls/$id/ws'
      preLoaderRoute: typeof ApiPollsIdWsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AcceptInvitationIdRoute: AcceptInvitationIdRoute,
  ApiHealthRoute: ApiHealthRoute,
  BookingsNewRoute: BookingsNewRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStatsWsRoute: ApiStatsWsRoute,
  ApiTestSeedRoute: ApiTestSeedRoute,
  BookHandleSlugRoute: BookHandleSlugRoute,
  BookingIdCalendarDoticsRoute: BookingIdCalendarDoticsRoute,
  BookingsIdEditRoute: BookingsIdEditRoute,
  PIdCalendarDoticsRoute: PIdCalendarDoticsRoute,
  PIdEditRoute: PIdEditRoute,
  PIdRosterDotcsvRoute: PIdRosterDotcsvRoute,
  BookingIdIndexRoute: BookingIdIndexRoute,
  BookingsIdIndexRoute: BookingsIdIndexRoute,
  PIdIndexRoute: PIdIndexRoute,
  ApiBookingsPageIdWsRoute: ApiBookingsPageIdWsRoute,
  ApiPollsIdWsRoute: ApiPollsIdWsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
